#!/usr/bin/env bash
# ==============================================================================
# 05-bashrc-preserve.sh — bashrc_preserve() utility
#
# Snapshots any aliases in your current shell that are NOT defined by this
# repo's .bashrc.d/ scripts into ~/.bashrc.d/60-local-aliases.sh.
#
# This preserves personal customizations (opencode session shortcuts, project
# aliases, custom tools) across repo updates and machine migrations.
#
# Usage:
#   bashrc_preserve          — snapshot unknown aliases to 60-local-aliases.sh
#   bashrc_preserve --dry-run — show what would be written without writing
#   bashrc_preserve --show   — print current contents of 60-local-aliases.sh
# ==============================================================================

function bashrc_preserve() {
    local dry_run=0 show=0
    local output_file="${HOME}/.bashrc.d/60-local-aliases.sh"
    local repo_dir

    # Parse args
    for arg in "$@"; do
        case "$arg" in
            --dry-run) dry_run=1 ;;
            --show)    show=1 ;;
        esac
    done

    # --show: just print current file
    if (( show )); then
        if [[ -f "$output_file" ]]; then
            echo "=== ${output_file} ==="
            cat "$output_file"
        else
            echo "No local aliases file found at ${output_file}"
        fi
        return 0
    fi

    # Find the repo root (this script lives in .bashrc.d/)
    repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." 2>/dev/null && pwd)"
    if [[ -z "$repo_dir" || ! -d "$repo_dir/.bashrc.d" ]]; then
        # Fallback: look for the repo in common locations
        for candidate in \
            "${HOME}/source/repos/bash_environment" \
            "${HOME}/git/bash_environment" \
            "${HOME}/repos/bash_environment"; do
            if [[ -d "$candidate/.bashrc.d" ]]; then
                repo_dir="$candidate"
                break
            fi
        done
    fi

    if [[ -z "$repo_dir" ]]; then
        echo "bashrc_preserve: cannot locate bash_environment repo" >&2
        return 1
    fi

    # Step 1: collect ALL aliases defined by repo scripts in a clean subshell
    local repo_aliases
    repo_aliases=$(bash --norc --noprofile -c "
        for f in \"${repo_dir}\"/.bashrc.d/*.sh; do
            [[ -f \"\$f\" ]] || continue
            # Skip this script and the output file to avoid recursion
            case \"\${f##*/}\" in
                05-bashrc-preserve.sh|60-local-aliases.sh) continue ;;
            esac
            source \"\$f\" 2>/dev/null
        done
        alias
    " 2>/dev/null | sed "s/^alias //" | cut -d= -f1 | sort)

    # Step 2: collect ALL aliases in the current live shell
    local live_aliases
    live_aliases=$(alias 2>/dev/null | sed "s/^alias //" | sort)

    # Step 3: diff — keep only aliases NOT in the repo set
    # Also filter out: shell builtins, functions, anything starting with _
    local custom_aliases=()
    while IFS= read -r line; do
        local aname="${line%%=*}"
        # Skip private/internal aliases
        [[ "$aname" == _* ]] && continue
        # Skip if defined by repo
        if ! grep -qx "$aname" <<< "$repo_aliases" 2>/dev/null; then
            custom_aliases+=("$line")
        fi
    done <<< "$live_aliases"

    if (( ${#custom_aliases[@]} == 0 )); then
        echo "bashrc_preserve: no custom aliases found — nothing to write"
        return 0
    fi

    # Step 4: build the output
    local header
    printf -v header '%(%Y-%m-%d %H:%M:%S)T' -1
    local content
    content="#!/usr/bin/env bash
# ==============================================================================
# ~/.bashrc.d/60-local-aliases.sh — Local alias preservation
#
# GENERATED by bashrc_preserve() on ${header}
# DO NOT EDIT by hand — run 'bashrc_preserve' to regenerate.
#
# Contains aliases present in your shell but NOT defined by bash_environment.
# Preserves personal customizations across repo updates and migrations.
# ==============================================================================

"
    for alias_line in "${custom_aliases[@]}"; do
        content+="alias ${alias_line}"$'\n'
    done

    # Step 5: write or dry-run
    if (( dry_run )); then
        echo "=== DRY RUN — would write ${output_file} ==="
        echo "${content}"
        echo "(${#custom_aliases[@]} custom aliases found)"
    else
        echo "${content}" > "$output_file"
        echo "bashrc_preserve: wrote ${#custom_aliases[@]} custom aliases to ${output_file}"
        # Show what was saved
        printf "  %s\n" "${custom_aliases[@]%%=*}"
    fi
}
