#!/usr/bin/env bash
# ==============================================================================
# ~/.bashrc.d/60-local-aliases.sh — Local alias preservation
#
# This file is GENERATED by bashrc_preserve() — do not edit by hand.
# Run 'bashrc_preserve' to regenerate from your current shell environment.
#
# It captures aliases that exist in your shell but are NOT defined by any
# script in this repo's .bashrc.d/ — preserving personal customizations
# across repo updates and machine migrations.
# ==============================================================================
